spring:
  application:
    name: user-service

server:
  port: 8081
  address: 0.0.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/

info:
  app:
    name: user-service
    description: Spring Cloud Application Managing Person Instances
    version: 1.0-SNAPSHOT