spring:
  application:
    name: discovery-service
  cloud:
    config.server.git.uri: "https://github.com/c-cri35/spring-config-server.git"

server:
  port: 3000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: DEBUG
    com.apress.cems: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
